version: '3.8'

services:
  eureka-server:
    build: .
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/
      - spring.security.user.name=admin
      - spring.security.user.password=secret
    volumes:
      - ./src/main/resources:/config
    networks:
      - eureka-network

networks:
  auth_net:
    name: authentication-service_default
