version: '3.8'

services:
  eureka-server:
    build: .
    container_name: eureka-server
    environment:
      SPRING_CONFIG_LOCATION: classpath:/application-test.properties
    ports:
      - "8761:8761"
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
